Fix for broken LoadBalancers.getAll function
matt-major/do-wrapper pull request #62
Opened 2020-11-30 16:36 UTC by goodlime

LoadBalancers.getAll() was failing with the following error:

`{ HTTPError: Response code 404 (Not Found)
    at EventEmitter.emitter.on (/app/node_modules/do-wrapper-fork/node_modules/got/dist/source/as-promise.js:118:31)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'HTTPError' }`

Debugging this issue resulted in finding that a trailing slash in the API endpoint URL was causing the DO API to look for an ID after the trailing slash. Remove trailing slash from LoadBalancers `basePath` variable fixes this issue.

I am not sure if this was caused by an issue with the DO API itself, but this fix works for LoadBalancers in do-wrapper. I have not tested whether the LoadBalancers.create function is affected by this pull request. All other calls within the LoadBalancers module utilize a custom `actionPath` and will not be affected by this change.

2020-12-22 18:03 UTC, matt-major commented on dist/modules/domains.js
> +        console.log('body:', options);
Can you remove these please?

2020-12-22 18:04 UTC, matt-major commented
@goodlime  apologies for the delay on picking this up. I'd be happy to review the PR but it looks like you have only changed the `dist` files and not the source `.ts` ones, so this would be overwritten on the next build. 

Please correct and I will review for you.

Thanks!

2020-12-22 20:16 UTC, matt-major requested changes
Only `dist` files changed, need source files changing for this to be reviewed

2020-12-28 14:13 UTC, goodlime commented
Appologies, I polluted the PR with some logging I had added subsequently. Should be good to go now.

2021-01-13 19:18 UTC, matt-major approved these changes

2021-01-13 19:18 UTC, merged

2021-01-13 19:19 UTC, matt-major commented
@goodlime apologies for the delay, approved and published now. Thanks!